"""add filename to enrollment assets

Revision ID: 1a44f9eaf8c3
Revises: 249b317ca3b5
Create Date: 2026-08-14 23:46:16.320300
"""

from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

revision: str = "1a44f9eaf8c3"
down_revision: str | None = "249b317ca3b5"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_admin_sessions_admin_user_active"), table_name="admin_sessions")
    op.drop_index(op.f("ix_admin_users_role"), table_name="admin_users")
    op.add_column(
        "enrollment_assets",
        sa.Column("filename", sa.String(length=255), server_default="capture", nullable=False),
    )
    op.alter_column(
        "people",
        "merged_at",
        existing_type=postgresql.TIMESTAMP(timezone=True),
        type_=sa.DateTime(),
        existing_nullable=True,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "people",
        "merged_at",
        existing_type=sa.DateTime(),
        type_=postgresql.TIMESTAMP(timezone=True),
        existing_nullable=True,
    )
    op.drop_column("enrollment_assets", "filename")
    op.create_index(op.f("ix_admin_users_role"), "admin_users", ["role"], unique=False)
    op.create_index(
        op.f("ix_admin_sessions_admin_user_active"),
        "admin_sessions",
        ["admin_user_id", "revoked_at"],
        unique=False,
    )
    # ### end Alembic commands ###
