"""add_notifications_tables

Revision ID: 249b317ca3b5
Revises: 591d22945307
Create Date: 2026-08-14 23:15:50.862252
"""
from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

revision: str = '249b317ca3b5'
down_revision: str | None = '591d22945307'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('notification_rules',
    sa.Column('id', sa.Uuid(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('group_id', sa.Uuid(), nullable=True),
    sa.Column('person_kind', sa.String(length=32), nullable=True),
    sa.Column('trigger_status', sa.String(length=32), nullable=False),
    sa.Column('delay_minutes', sa.Integer(), nullable=False),
    sa.Column('channel', sa.String(length=32), nullable=False),
    sa.Column('template', sa.Text(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('delay_minutes >= 0', name=op.f('ck_notification_rules_delay_minutes_non_negative')),
    sa.ForeignKeyConstraint(['group_id'], ['groups.id'], name=op.f('fk_notification_rules_group_id_groups'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_notification_rules'))
    )
    op.create_table('notifications',
    sa.Column('id', sa.Uuid(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('person_id', sa.Uuid(), nullable=False),
    sa.Column('business_date', sa.Date(), nullable=False),
    sa.Column('shift_id', sa.Uuid(), nullable=False),
    sa.Column('period_label', sa.String(length=64), nullable=False),
    sa.Column('guardian_id', sa.Uuid(), nullable=False),
    sa.Column('type', sa.String(length=32), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('channel', sa.String(length=32), nullable=False),
    sa.Column('recipient', sa.String(length=320), nullable=False),
    sa.Column('message_body', sa.Text(), nullable=False),
    sa.Column('dedupe_key', sa.String(length=256), nullable=False),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('sent_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('scheduled_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("dedupe_key <> ''", name=op.f('ck_notifications_dedupe_key_non_empty')),
    sa.ForeignKeyConstraint(['guardian_id'], ['guardians.id'], name=op.f('fk_notifications_guardian_id_guardians'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['person_id'], ['people.id'], name=op.f('fk_notifications_person_id_people'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_notifications')),
    sa.UniqueConstraint('dedupe_key', name='uq_notifications_dedupe_key')
    )
    op.create_index('ix_notifications_person_date', 'notifications', ['person_id', 'business_date'], unique=False)
    op.create_index('ix_notifications_status', 'notifications', ['status'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_notifications_status', table_name='notifications')
    op.drop_index('ix_notifications_person_date', table_name='notifications')
    op.drop_table('notifications')
    op.drop_table('notification_rules')
    # ### end Alembic commands ###
