"""add deactivated_at to people

Revision ID: 8fa6501f8b67
Revises: 9c5d350d9ecb
Create Date: 2026-08-18 17:14:57.921431
"""
from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

revision: str = '8fa6501f8b67'
down_revision: str | None = '9c5d350d9ecb'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('people', sa.Column('deactivated_at', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('people', 'deactivated_at')
    # ### end Alembic commands ###
