"""phase 2 model tables

Revision ID: dade611d4072
Revises: 0001_database_foundation
Create Date: 2026-07-31 21:19:02.152456
"""

from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

revision: str = "dade611d4072"
down_revision: str | None = "0001_database_foundation"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "groups",
        sa.Column("id", sa.Uuid(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.Column("parent_group_id", sa.Uuid(), nullable=True),
        sa.Column("kind", sa.String(length=32), nullable=False),
        sa.Column("name", sa.String(length=256), nullable=False),
        sa.Column("code", sa.String(length=64), nullable=True),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint("name <> ''", name=op.f("ck_groups_name_non_empty")),
        sa.ForeignKeyConstraint(
            ["parent_group_id"],
            ["groups.id"],
            name=op.f("fk_groups_parent_group_id_groups"),
            ondelete="SET NULL",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_groups")),
        sa.UniqueConstraint("parent_group_id", "name", name="uq_groups_parent_name"),
    )
    op.create_table(
        "guardians",
        sa.Column("id", sa.Uuid(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.Column("display_name", sa.String(length=256), nullable=False),
        sa.Column("email", sa.String(length=320), nullable=True),
        sa.Column("phone", sa.String(length=64), nullable=True),
        sa.Column("preferred_channel", sa.String(length=32), nullable=False),
        sa.Column("locale", sa.String(length=16), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint("display_name <> ''", name=op.f("ck_guardians_display_name_non_empty")),
        sa.CheckConstraint(
            "email IS NOT NULL OR phone IS NOT NULL",
            name=op.f("ck_guardians_guardian_has_contact_channel"),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_guardians")),
    )
    op.create_table(
        "locations",
        sa.Column("id", sa.Uuid(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.Column("name", sa.String(length=256), nullable=False),
        sa.Column("timezone", sa.String(length=64), nullable=False),
        sa.Column("latitude", sa.Numeric(precision=8, scale=6), nullable=True),
        sa.Column("longitude", sa.Numeric(precision=9, scale=6), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint("name <> ''", name=op.f("ck_locations_name_non_empty")),
        sa.CheckConstraint("timezone <> ''", name=op.f("ck_locations_timezone_non_empty")),
        sa.CheckConstraint(
            "latitude IS NULL OR latitude BETWEEN -90 AND 90",
            name=op.f("ck_locations_latitude_range"),
        ),
        sa.CheckConstraint(
            "longitude IS NULL OR longitude BETWEEN -180 AND 180",
            name=op.f("ck_locations_longitude_range"),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_locations")),
    )
    op.create_table(
        "people",
        sa.Column("id", sa.Uuid(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.Column("external_id", sa.String(length=128), nullable=True),
        sa.Column("kind", sa.String(length=32), nullable=False),
        sa.Column("display_name", sa.String(length=256), nullable=False),
        sa.Column("preferred_name", sa.String(length=256), nullable=True),
        sa.Column("locale", sa.String(length=16), nullable=False),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint("display_name <> ''", name=op.f("ck_people_display_name_non_empty")),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_people")),
        sa.UniqueConstraint("external_id", name="uq_people_external_id"),
    )
    op.create_table(
        "schedules",
        sa.Column("id", sa.Uuid(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.Column("name", sa.String(length=128), nullable=False),
        sa.Column("effective_from", sa.Date(), nullable=False),
        sa.Column("effective_to", sa.Date(), nullable=True),
        sa.Column("timezone", sa.String(length=64), nullable=True),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint("name <> ''", name=op.f("ck_schedules_name_non_empty")),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_schedules")),
        sa.UniqueConstraint("name", name="uq_schedules_name"),
    )
    op.create_table(
        "shifts",
        sa.Column("id", sa.Uuid(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.Column("name", sa.String(length=128), nullable=False),
        sa.Column("starts_at", sa.Time(), nullable=False),
        sa.Column("ends_at", sa.Time(), nullable=False),
        sa.Column("crosses_midnight", sa.Boolean(), nullable=False),
        sa.Column("grace_in_minutes", sa.Integer(), nullable=False),
        sa.Column("grace_out_minutes", sa.Integer(), nullable=False),
        sa.Column("absent_after_minutes", sa.Integer(), nullable=False),
        sa.Column("auto_close_minutes", sa.Integer(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint("name <> ''", name=op.f("ck_shifts_name_non_empty")),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_shifts")),
        sa.UniqueConstraint("name", name="uq_shifts_name"),
    )
    op.create_table(
        "attendance_overrides",
        sa.Column("id", sa.Uuid(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.Column("person_id", sa.Uuid(), nullable=False),
        sa.Column("business_date", sa.Date(), nullable=False),
        sa.Column("shift_id", sa.Uuid(), nullable=False),
        sa.Column("period_label", sa.String(length=64), server_default="", nullable=False),
        sa.Column("status", sa.String(length=32), nullable=False),
        sa.Column("reason", sa.String(length=512), nullable=False),
        sa.Column("actor_admin_id", sa.Uuid(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint("reason <> ''", name=op.f("ck_attendance_overrides_reason_non_empty")),
        sa.CheckConstraint(
            "period_label IS NOT NULL", name=op.f("ck_attendance_overrides_period_label_not_null")
        ),
        sa.ForeignKeyConstraint(
            ["person_id"],
            ["people.id"],
            name=op.f("fk_attendance_overrides_person_id_people"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["shift_id"],
            ["shifts.id"],
            name=op.f("fk_attendance_overrides_shift_id_shifts"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_attendance_overrides")),
        sa.UniqueConstraint(
            "person_id",
            "business_date",
            "shift_id",
            "period_label",
            name="uq_attendance_overrides_natural_key",
        ),
    )
    op.create_table(
        "calendar_days",
        sa.Column("id", sa.Uuid(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.Column("location_id", sa.Uuid(), nullable=False),
        sa.Column("business_date", sa.Date(), nullable=False),
        sa.Column("kind", sa.String(length=32), nullable=False),
        sa.Column("label", sa.String(length=128), nullable=False),
        sa.Column("is_working_day", sa.Boolean(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint("label <> ''", name=op.f("ck_calendar_days_label_non_empty")),
        sa.ForeignKeyConstraint(
            ["location_id"],
            ["locations.id"],
            name=op.f("fk_calendar_days_location_id_locations"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_calendar_days")),
        sa.UniqueConstraint("location_id", "business_date", name="uq_calendar_days_location_date"),
    )
    op.create_table(
        "consents",
        sa.Column("id", sa.Uuid(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.Column("person_id", sa.Uuid(), nullable=False),
        sa.Column("guardian_id", sa.Uuid(), nullable=True),
        sa.Column("consent_type", sa.String(length=64), nullable=False),
        sa.Column("grantor", sa.String(length=32), nullable=False),
        sa.Column("grantor_relationship", sa.String(length=64), nullable=True),
        sa.Column("method", sa.String(length=64), nullable=False),
        sa.Column("policy_version", sa.String(length=64), nullable=False),
        sa.Column("granted_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("revoked_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("ip_address", sa.String(length=64), nullable=True),
        sa.Column("evidence_ref", sa.String(length=512), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "grantor <> 'guardian' OR guardian_id IS NOT NULL",
            name=op.f("ck_consents_guardian_consent_requires_guardian"),
        ),
        sa.CheckConstraint(
            "policy_version <> ''", name=op.f("ck_consents_policy_version_non_empty")
        ),
        sa.CheckConstraint(
            "revoked_at IS NULL OR revoked_at >= granted_at",
            name=op.f("ck_consents_revoked_at_not_before_granted_at"),
        ),
        sa.ForeignKeyConstraint(
            ["guardian_id"],
            ["guardians.id"],
            name=op.f("fk_consents_guardian_id_guardians"),
            ondelete="SET NULL",
        ),
        sa.ForeignKeyConstraint(
            ["person_id"],
            ["people.id"],
            name=op.f("fk_consents_person_id_people"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_consents")),
        sa.UniqueConstraint(
            "person_id",
            "consent_type",
            "policy_version",
            name="uq_consents_person_type_policy_version",
        ),
    )
    op.create_table(
        "devices",
        sa.Column("id", sa.Uuid(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.Column("location_id", sa.Uuid(), nullable=True),
        sa.Column("mode", sa.String(length=16), nullable=False),
        sa.Column("form_factor", sa.String(length=16), nullable=False),
        sa.Column("direction", sa.String(length=16), nullable=False),
        sa.Column("token_hash", sa.String(length=255), nullable=False),
        sa.Column("token_display_prefix", sa.String(length=32), nullable=False),
        sa.Column("pairing_code_hash", sa.String(length=255), nullable=True),
        sa.Column("pairing_code_expires_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("settings_override", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("allowed_cidrs", postgresql.ARRAY(sa.Text()), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "direction IN ('in', 'out', 'bidirectional')", name=op.f("ck_devices_direction_valid")
        ),
        sa.CheckConstraint(
            "form_factor IN ('phone', 'tablet', 'desktop')",
            name=op.f("ck_devices_form_factor_valid"),
        ),
        sa.CheckConstraint(
            "mode <> 'fixed' OR location_id IS NOT NULL",
            name=op.f("ck_devices_fixed_devices_require_location"),
        ),
        sa.CheckConstraint("mode IN ('fixed', 'roaming')", name=op.f("ck_devices_mode_valid")),
        sa.CheckConstraint(
            "token_display_prefix <> ''", name=op.f("ck_devices_token_display_prefix_non_empty")
        ),
        sa.CheckConstraint("token_hash <> ''", name=op.f("ck_devices_token_hash_non_empty")),
        sa.CheckConstraint(
            "pairing_code_hash IS NULL OR pairing_code_expires_at IS NOT NULL",
            name=op.f("ck_devices_pairing_code_requires_expiry"),
        ),
        sa.ForeignKeyConstraint(
            ["location_id"],
            ["locations.id"],
            name=op.f("fk_devices_location_id_locations"),
            ondelete="SET NULL",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_devices")),
    )
    op.create_table(
        "expected_attendance",
        sa.Column("id", sa.Uuid(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.Column("person_id", sa.Uuid(), nullable=False),
        sa.Column("business_date", sa.Date(), nullable=False),
        sa.Column("shift_id", sa.Uuid(), nullable=False),
        sa.Column("period_label", sa.String(length=64), server_default="", nullable=False),
        sa.Column("location_id", sa.Uuid(), nullable=True),
        sa.Column("schedule_id", sa.Uuid(), nullable=True),
        sa.Column("expected_start_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("expected_end_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("absent_after_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("is_working_day", sa.Boolean(), nullable=False),
        sa.Column("voided_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "expected_end_at > expected_start_at",
            name=op.f("ck_expected_attendance_expected_end_after_start"),
        ),
        sa.CheckConstraint(
            "period_label IS NOT NULL", name=op.f("ck_expected_attendance_period_label_not_null")
        ),
        sa.ForeignKeyConstraint(
            ["location_id"],
            ["locations.id"],
            name=op.f("fk_expected_attendance_location_id_locations"),
            ondelete="SET NULL",
        ),
        sa.ForeignKeyConstraint(
            ["person_id"],
            ["people.id"],
            name=op.f("fk_expected_attendance_person_id_people"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["schedule_id"],
            ["schedules.id"],
            name=op.f("fk_expected_attendance_schedule_id_schedules"),
            ondelete="SET NULL",
        ),
        sa.ForeignKeyConstraint(
            ["shift_id"],
            ["shifts.id"],
            name=op.f("fk_expected_attendance_shift_id_shifts"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_expected_attendance")),
        sa.UniqueConstraint(
            "person_id",
            "business_date",
            "shift_id",
            "period_label",
            name="uq_expected_attendance_natural_key",
        ),
    )
    op.create_index(
        "ix_expected_attendance_business_date",
        "expected_attendance",
        ["business_date"],
        unique=False,
    )
    op.create_table(
        "person_exceptions",
        sa.Column("id", sa.Uuid(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.Column("person_id", sa.Uuid(), nullable=False),
        sa.Column("business_date", sa.Date(), nullable=False),
        sa.Column("kind", sa.String(length=32), nullable=False),
        sa.Column("reason", sa.String(length=512), nullable=False),
        sa.Column("created_by_admin_id", sa.Uuid(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint("reason <> ''", name=op.f("ck_person_exceptions_reason_non_empty")),
        sa.ForeignKeyConstraint(
            ["person_id"],
            ["people.id"],
            name=op.f("fk_person_exceptions_person_id_people"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_person_exceptions")),
        sa.UniqueConstraint(
            "person_id", "business_date", "kind", name="uq_person_exceptions_person_date_kind"
        ),
    )
    op.create_table(
        "person_groups",
        sa.Column("id", sa.Uuid(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.Column("person_id", sa.Uuid(), nullable=False),
        sa.Column("group_id", sa.Uuid(), nullable=False),
        sa.Column("effective_from", sa.Date(), nullable=False),
        sa.Column("effective_to", sa.Date(), nullable=True),
        sa.Column("is_primary", sa.Boolean(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "effective_to IS NULL OR effective_to >= effective_from",
            name=op.f("ck_person_groups_effective_to_not_before_from"),
        ),
        sa.ForeignKeyConstraint(
            ["group_id"],
            ["groups.id"],
            name=op.f("fk_person_groups_group_id_groups"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["person_id"],
            ["people.id"],
            name=op.f("fk_person_groups_person_id_people"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_person_groups")),
        sa.UniqueConstraint(
            "person_id",
            "group_id",
            "effective_from",
            name="uq_person_groups_person_group_effective_from",
        ),
    )
    op.create_table(
        "person_guardians",
        sa.Column("id", sa.Uuid(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.Column("person_id", sa.Uuid(), nullable=False),
        sa.Column("guardian_id", sa.Uuid(), nullable=False),
        sa.Column("relationship", sa.String(length=32), nullable=False),
        sa.Column("can_pick_up", sa.Boolean(), nullable=False),
        sa.Column("receives_attendance_alerts", sa.Boolean(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["guardian_id"],
            ["guardians.id"],
            name=op.f("fk_person_guardians_guardian_id_guardians"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["person_id"],
            ["people.id"],
            name=op.f("fk_person_guardians_person_id_people"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_person_guardians")),
        sa.UniqueConstraint("person_id", "guardian_id", name="uq_person_guardians_person_guardian"),
    )
    op.create_table(
        "schedule_assignments",
        sa.Column("id", sa.Uuid(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.Column("schedule_id", sa.Uuid(), nullable=False),
        sa.Column("scope", sa.String(length=32), nullable=False),
        sa.Column("scope_id", sa.Uuid(), nullable=True),
        sa.Column("priority", sa.Integer(), nullable=False),
        sa.Column("effective_from", sa.Date(), nullable=False),
        sa.Column("effective_to", sa.Date(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "scope = 'org' OR scope_id IS NOT NULL",
            name=op.f("ck_schedule_assignments_non_org_scope_requires_scope_id"),
        ),
        sa.CheckConstraint(
            "effective_to IS NULL OR effective_to >= effective_from",
            name=op.f("ck_schedule_assignments_effective_to_not_before_from"),
        ),
        sa.ForeignKeyConstraint(
            ["schedule_id"],
            ["schedules.id"],
            name=op.f("fk_schedule_assignments_schedule_id_schedules"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_schedule_assignments")),
        sa.UniqueConstraint(
            "scope",
            "scope_id",
            "effective_from",
            "schedule_id",
            name="uq_schedule_assignments_scope_effective_schedule",
        ),
    )
    op.create_table(
        "schedule_rules",
        sa.Column("id", sa.Uuid(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.Column("schedule_id", sa.Uuid(), nullable=False),
        sa.Column("shift_id", sa.Uuid(), nullable=True),
        sa.Column("weekday", sa.Integer(), nullable=False),
        sa.Column("is_working_day", sa.Boolean(), nullable=False),
        sa.Column("period_label", sa.String(length=64), server_default="", nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint("weekday BETWEEN 0 AND 6", name=op.f("ck_schedule_rules_weekday_range")),
        sa.ForeignKeyConstraint(
            ["schedule_id"],
            ["schedules.id"],
            name=op.f("fk_schedule_rules_schedule_id_schedules"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["shift_id"],
            ["shifts.id"],
            name=op.f("fk_schedule_rules_shift_id_shifts"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_schedule_rules")),
        sa.UniqueConstraint("schedule_id", "weekday", name="uq_schedule_rules_schedule_weekday"),
    )
    op.create_table(
        "attendance_events",
        sa.Column("id", sa.BigInteger(), sa.Identity(always=False), nullable=False),
        sa.Column("idempotency_key", sa.String(length=128), nullable=False),
        sa.Column("person_id", sa.Uuid(), nullable=True),
        sa.Column("device_id", sa.Uuid(), nullable=True),
        sa.Column("location_id", sa.Uuid(), nullable=True),
        sa.Column("shift_id", sa.Uuid(), nullable=True),
        sa.Column("supersedes_event_id", sa.BigInteger(), nullable=True),
        sa.Column("direction", sa.String(length=8), nullable=False),
        sa.Column("outcome", sa.String(length=32), nullable=False),
        sa.Column("location_source", sa.String(length=32), nullable=True),
        sa.Column("business_date", sa.Date(), nullable=True),
        sa.Column("device_local_date", sa.Date(), nullable=True),
        sa.Column("period_label", sa.String(length=64), server_default="", nullable=False),
        sa.Column("client_captured_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("server_received_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("occurred_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("monotonic_offset_ms", sa.Integer(), nullable=False),
        sa.Column("was_backdated", sa.Boolean(), nullable=False),
        sa.Column("top1_score", sa.Numeric(precision=6, scale=5), nullable=True),
        sa.Column("top2_other_person_score", sa.Numeric(precision=6, scale=5), nullable=True),
        sa.Column("metadata", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "idempotency_key <> ''", name=op.f("ck_attendance_events_idempotency_key_non_empty")
        ),
        sa.CheckConstraint(
            "monotonic_offset_ms >= 0",
            name=op.f("ck_attendance_events_monotonic_offset_ms_non_negative"),
        ),
        sa.CheckConstraint(
            "occurred_at <= server_received_at",
            name=op.f("ck_attendance_events_occurred_at_not_after_server_received"),
        ),
        sa.CheckConstraint(
            "period_label IS NOT NULL", name=op.f("ck_attendance_events_period_label_not_null")
        ),
        sa.CheckConstraint(
            "top1_score IS NULL OR top1_score BETWEEN 0 AND 1",
            name=op.f("ck_attendance_events_top1_score_probability_range"),
        ),
        sa.CheckConstraint(
            "top2_other_person_score IS NULL OR top2_other_person_score BETWEEN 0 AND 1",
            name=op.f("ck_attendance_events_top2_other_person_score_probability_range"),
        ),
        sa.ForeignKeyConstraint(
            ["device_id"],
            ["devices.id"],
            name=op.f("fk_attendance_events_device_id_devices"),
            ondelete="SET NULL",
        ),
        sa.ForeignKeyConstraint(
            ["location_id"],
            ["locations.id"],
            name=op.f("fk_attendance_events_location_id_locations"),
            ondelete="SET NULL",
        ),
        sa.ForeignKeyConstraint(
            ["person_id"],
            ["people.id"],
            name=op.f("fk_attendance_events_person_id_people"),
            ondelete="SET NULL",
        ),
        sa.ForeignKeyConstraint(
            ["shift_id"],
            ["shifts.id"],
            name=op.f("fk_attendance_events_shift_id_shifts"),
            ondelete="SET NULL",
        ),
        sa.ForeignKeyConstraint(
            ["supersedes_event_id"],
            ["attendance_events.id"],
            name=op.f("fk_attendance_events_supersedes_event_id_attendance_events"),
            ondelete="SET NULL",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_attendance_events")),
        sa.UniqueConstraint("idempotency_key", name="uq_attendance_events_idempotency_key"),
    )
    op.create_index(
        "ix_attendance_events_device_local_date",
        "attendance_events",
        ["device_id", "device_local_date"],
        unique=False,
    )
    op.create_index(
        "ix_attendance_events_person_business_date",
        "attendance_events",
        ["person_id", "business_date"],
        unique=False,
    )
    op.create_table(
        "device_heartbeats",
        sa.Column("id", sa.BigInteger(), sa.Identity(always=False), nullable=False),
        sa.Column("device_id", sa.Uuid(), nullable=False),
        sa.Column("observed_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("battery_pct", sa.Integer(), nullable=True),
        sa.Column("clock_skew_ms", sa.Integer(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "battery_pct IS NULL OR battery_pct BETWEEN 0 AND 100",
            name=op.f("ck_device_heartbeats_battery_pct_range"),
        ),
        sa.ForeignKeyConstraint(
            ["device_id"],
            ["devices.id"],
            name=op.f("fk_device_heartbeats_device_id_devices"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_device_heartbeats")),
    )
    op.create_table(
        "enrollment_assets",
        sa.Column("id", sa.Uuid(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.Column("person_id", sa.Uuid(), nullable=False),
        sa.Column("consent_id", sa.Uuid(), nullable=False),
        sa.Column("kind", sa.String(length=32), nullable=False),
        sa.Column("capture_pose", sa.String(length=32), nullable=False),
        sa.Column("content_type", sa.String(length=128), nullable=False),
        sa.Column("byte_size", sa.Integer(), nullable=False),
        sa.Column("checksum_sha256", sa.String(length=64), nullable=False),
        sa.Column("captured_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("envelope_version", sa.Integer(), nullable=False),
        sa.Column("payload_alg", sa.String(length=64), nullable=False),
        sa.Column("dek_wrap_alg", sa.String(length=64), nullable=False),
        sa.Column("encryption_key_id", sa.String(length=128), nullable=False),
        sa.Column("wrapped_dek", sa.LargeBinary(), nullable=False),
        sa.Column("dek_nonce", sa.LargeBinary(), nullable=False),
        sa.Column("payload_nonce", sa.LargeBinary(), nullable=False),
        sa.Column("ciphertext", sa.LargeBinary(), nullable=False),
        sa.CheckConstraint(
            "capture_pose <> ''", name=op.f("ck_enrollment_assets_capture_pose_non_empty")
        ),
        sa.CheckConstraint(
            "content_type <> ''", name=op.f("ck_enrollment_assets_content_type_non_empty")
        ),
        sa.CheckConstraint("byte_size > 0", name=op.f("ck_enrollment_assets_byte_size_positive")),
        sa.ForeignKeyConstraint(
            ["consent_id"],
            ["consents.id"],
            name=op.f("fk_enrollment_assets_consent_id_consents"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["person_id"],
            ["people.id"],
            name=op.f("fk_enrollment_assets_person_id_people"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_enrollment_assets")),
    )
    op.create_table(
        "attendance_records",
        sa.Column("id", sa.Uuid(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.Column("expected_attendance_id", sa.Uuid(), nullable=True),
        sa.Column("override_id", sa.Uuid(), nullable=True),
        sa.Column("person_id", sa.Uuid(), nullable=False),
        sa.Column("business_date", sa.Date(), nullable=False),
        sa.Column("shift_id", sa.Uuid(), nullable=False),
        sa.Column("period_label", sa.String(length=64), server_default="", nullable=False),
        sa.Column("status", sa.String(length=32), nullable=False),
        sa.Column("first_event_id", sa.BigInteger(), nullable=True),
        sa.Column("last_event_id", sa.BigInteger(), nullable=True),
        sa.Column("late_minutes", sa.Integer(), nullable=True),
        sa.Column("flags", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("resolved_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "late_minutes IS NULL OR late_minutes >= 0",
            name=op.f("ck_attendance_records_late_minutes_non_negative"),
        ),
        sa.CheckConstraint(
            "period_label IS NOT NULL", name=op.f("ck_attendance_records_period_label_not_null")
        ),
        sa.ForeignKeyConstraint(
            ["expected_attendance_id"],
            ["expected_attendance.id"],
            name=op.f("fk_attendance_records_expected_attendance_id_expected_attendance"),
            ondelete="SET NULL",
        ),
        sa.ForeignKeyConstraint(
            ["first_event_id"],
            ["attendance_events.id"],
            name=op.f("fk_attendance_records_first_event_id_attendance_events"),
            ondelete="SET NULL",
        ),
        sa.ForeignKeyConstraint(
            ["last_event_id"],
            ["attendance_events.id"],
            name=op.f("fk_attendance_records_last_event_id_attendance_events"),
            ondelete="SET NULL",
        ),
        sa.ForeignKeyConstraint(
            ["override_id"],
            ["attendance_overrides.id"],
            name=op.f("fk_attendance_records_override_id_attendance_overrides"),
            ondelete="SET NULL",
        ),
        sa.ForeignKeyConstraint(
            ["person_id"],
            ["people.id"],
            name=op.f("fk_attendance_records_person_id_people"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["shift_id"],
            ["shifts.id"],
            name=op.f("fk_attendance_records_shift_id_shifts"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_attendance_records")),
        sa.UniqueConstraint(
            "person_id",
            "business_date",
            "shift_id",
            "period_label",
            name="uq_attendance_records_natural_key",
        ),
    )
    op.create_index(
        "ix_attendance_records_business_date_status",
        "attendance_records",
        ["business_date", "status"],
        unique=False,
    )
    op.create_table(
        "face_embeddings",
        sa.Column("id", sa.Uuid(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.Column("person_id", sa.Uuid(), nullable=False),
        sa.Column("consent_id", sa.Uuid(), nullable=False),
        sa.Column("asset_id", sa.Uuid(), nullable=True),
        sa.Column("model_name", sa.String(length=128), nullable=False),
        sa.Column("model_version", sa.String(length=128), nullable=False),
        sa.Column("embedding_dimensions", sa.Integer(), nullable=False),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.Column("quality", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("envelope_version", sa.Integer(), nullable=False),
        sa.Column("payload_alg", sa.String(length=64), nullable=False),
        sa.Column("dek_wrap_alg", sa.String(length=64), nullable=False),
        sa.Column("encryption_key_id", sa.String(length=128), nullable=False),
        sa.Column("wrapped_dek", sa.LargeBinary(), nullable=False),
        sa.Column("dek_nonce", sa.LargeBinary(), nullable=False),
        sa.Column("payload_nonce", sa.LargeBinary(), nullable=False),
        sa.Column("ciphertext", sa.LargeBinary(), nullable=False),
        sa.CheckConstraint(
            "model_name <> ''", name=op.f("ck_face_embeddings_model_name_non_empty")
        ),
        sa.CheckConstraint(
            "model_version <> ''", name=op.f("ck_face_embeddings_model_version_non_empty")
        ),
        sa.CheckConstraint(
            "embedding_dimensions = 512", name=op.f("ck_face_embeddings_embedding_dimensions_512")
        ),
        sa.ForeignKeyConstraint(
            ["asset_id"],
            ["enrollment_assets.id"],
            name=op.f("fk_face_embeddings_asset_id_enrollment_assets"),
            ondelete="SET NULL",
        ),
        sa.ForeignKeyConstraint(
            ["consent_id"],
            ["consents.id"],
            name=op.f("fk_face_embeddings_consent_id_consents"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["person_id"],
            ["people.id"],
            name=op.f("fk_face_embeddings_person_id_people"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_face_embeddings")),
        sa.UniqueConstraint(
            "person_id",
            "model_name",
            "model_version",
            "asset_id",
            name="uq_face_embeddings_person_model_asset",
        ),
    )
    op.create_index(
        "uq_face_embeddings_active_person_model",
        "face_embeddings",
        ["person_id", "model_name", "model_version"],
        unique=True,
        postgresql_where=sa.text("is_active"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute("DROP INDEX IF EXISTS uq_face_embeddings_active_person_model")
    op.drop_table("face_embeddings")
    op.drop_index("ix_attendance_records_business_date_status", table_name="attendance_records")
    op.drop_table("attendance_records")
    op.drop_table("enrollment_assets")
    op.drop_table("device_heartbeats")
    op.drop_index("ix_attendance_events_person_business_date", table_name="attendance_events")
    op.drop_index("ix_attendance_events_device_local_date", table_name="attendance_events")
    op.drop_table("attendance_events")
    op.drop_table("schedule_rules")
    op.drop_table("schedule_assignments")
    op.drop_table("person_guardians")
    op.drop_table("person_groups")
    op.drop_table("person_exceptions")
    op.drop_index("ix_expected_attendance_business_date", table_name="expected_attendance")
    op.drop_table("expected_attendance")
    op.drop_table("devices")
    op.drop_table("consents")
    op.drop_table("calendar_days")
    op.drop_table("attendance_overrides")
    op.drop_table("shifts")
    op.drop_table("schedules")
    op.drop_table("people")
    op.drop_table("locations")
    op.drop_table("guardians")
    op.drop_table("groups")
    # ### end Alembic commands ###
