// Generated by scripts/generate_protocol_ts.py. Do not edit by hand.

export type ClientMessageType = "hello" | "heartbeat" | "frame_burst";
export type ServerMessageType =
  | "ready"
  | "detected"
  | "checking"
  | "result"
  | "settings_push"
  | "backpressure"
  | "error";

export interface Hello {
  type: "hello";
  device_token_jwt: string;
  app_version: string;
  camera_label?: string | null;
}

export interface Heartbeat {
  type: "heartbeat";
  fps: number;
  queue_depth: number;
  error_count: number;
  clock_skew_ms: number;
}

export interface FrameItem {
  jpeg_b64: string;
  bbox: [number, number, number, number];
  monotonic_offset_ms: number;
}

export interface GateMetrics {
  bbox_area_pct?: number | null;
  interocular_px?: number | null;
  center_offset_pct?: number | null;
  sharpness?: number | null;
  luma?: number | null;
  stability_iou?: number | null;
  stability_frames?: number | null;
}

export interface FrameBurst {
  type: "frame_burst";
  idempotency_key: string;
  burst_seq: number;
  frames: FrameItem[];
  gate_metrics?: GateMetrics | null;
}

export type ClientMessage = Hello | Heartbeat | FrameBurst;

export interface Ready {
  type: "ready";
  gallery_version: number;
  settings_version: number;
}

export interface Detected {
  type: "detected";
}

export interface Checking {
  type: "checking";
}

export interface Person {
  id: string;
  display_name: string;
  photo_url?: string | null;
}

export interface Result {
  type: "result";
  status: string;
  person?: Person | null;
  direction?: string | null;
  occurred_at: string;
  record_status?: string | null;
  committed: true;
}

export interface SettingsPush {
  type: "settings_push";
  settings_version: number;
  payload: Record<string, unknown>;
}

export interface Backpressure {
  type: "backpressure";
  retry_after_ms: number;
}

export type ErrorCode =
  | "NO_FACE"
  | "MULTIPLE_FACES"
  | "FACE_TOO_SMALL"
  | "LOW_QUALITY"
  | "LIVENESS_FAILED"
  | "AMBIGUOUS"
  | "LOW_CONFIDENCE"
  | "UNKNOWN_FACE"
  | "COOLDOWN_ACTIVE"
  | "RATE_LIMITED"
  | "LOCATION_CONFLICT"
  | "DEVICE_REVOKED"
  | "SCAN_BACKEND_UNAVAILABLE"
  | "NO_CONSENT"
  | "DUPLICATE_ENROLLMENT";

export interface ErrorBody {
  code: ErrorCode;
  message: string;
  details?: Record<string, unknown> | null;
}

export interface ErrorMessage {
  type: "error";
  error: ErrorBody;
}

export type ServerMessage =
  | Ready
  | Detected
  | Checking
  | Result
  | SettingsPush
  | Backpressure
  | ErrorMessage;
